### ISSUE TITLE
Testimonials - Layout and font style is not correct as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/West-End-Charters#19]
![image](https://cloud.githubusercontent.com/assets/18587097/15661678/06e545d8-2714-11e6-9999-72dae8935381.png)

**Comment by napolgit** [comment]
Content edited by someone who use align center.

**Comment by napolgit** [comment]
Present layout was approved by Mario,
 please ignore the mock.

**Comment by napolgit** [comment]
Fixed on font  style.

**Comment by Atcharanak** [comment]
Please Provide a ticket mentioning the amends, If not fixed.
